name: build

on: push

jobs:
  run-test:
    runs-on: ubuntu-latest
    container:
      image: redis
    
    steps:
      - name: Running Tests
        run: redis-cli -h LOCAL ping
        
    services:
      LOCAL:
        image: redis
        ports:
          - 6379:6379
