name: build

on: push

jobs:
  run-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Running Tests
        run: docker run --network "host" redis redis-cli ping
        
    services:
      LOCAL:
        image: redis
        ports:
          - 6379:6379
